In [11]:
import numpy as np
import pickle
import pandas as pd

In [12]:
trj = pd.read_csv("classify_latest.csv")
trj = trj.sort_values(['clustr_id', 'Date'])
trj

,Author,Date,Rating,Helpful count,Review,Picture included,Language,(view source),tensor,aid,clustr_id,vec_2d
3204,ann tsai,2013-06-17 15:09:49,5,0,Good,no,NaN,view review,"tensor([[ 2.0482e-01, 3.3107e-01, 1.0315e+00...",39,0,"['2.0482e-01', ' 3.3107e-01', ' 1.0315e+00',..."
2104,Satoru Sato,2013-09-02 14:11:36,3,0,NaN,no,NaN,view review,"tensor([[ 2.0871e-01, 3.2975e-01, 1.0317e+00...",29,0,"['2.0871e-01', ' 3.2975e-01', ' 1.0317e+00',..."
4809,Patrick KalonjiTV,2014-08-09 03:54:44,5,0,Wow,no,NaN,view review,"tensor([[ 2.1687e-01, 3.2893e-01, 1.0362e+00...",53,0,"['2.1687e-01', ' 3.2893e-01', ' 1.0362e+00',..."
4810,Tú NguyễnNgoc,2015-02-26 11:18:57,5,0,My Dream,no,NaN,view review,"tensor([[ 2.0344e-01, 3.3022e-01, 1.0196e+00...",53,0,"['2.0344e-01', ' 3.3022e-01', ' 1.0196e+00',..."
1103,Chan mun kay,2015-04-16 06:58:29,4,0,Thanks,no,NaN,view review,"tensor([[ 2.1265e-01, 3.2680e-01, 1.0406e+00...",19,0,"['2.1265e-01', ' 3.2680e-01', ' 1.0406e+00',..."
...,...,...,...,...,...,...,...,...,...,...,...,...
4902,N,2023-05-30 15:24:51,5,0,"If you walk east from Demachiyanagi, you will...",yes,Japanese,view review,"tensor([[ 2.0703e-01, -4.1640e-02, 6.2501e-01...",53,99,"['2.0703e-01', ' -4.1640e-02', ' 6.2501e-01',..."
6702,えーちゃん2,2023-06-01 08:26:36,4,0,I visited Honen Shonin's 25 sacred grounds. I...,yes,Japanese,view review,"tensor([[ 2.0904e-01, 3.8601e-02, 5.7566e-01...",7,99,"['2.0904e-01', ' 3.8601e-02', ' 5.7566e-01',..."
2603,時々旅人,2023-06-04 08:17:14,5,1,It is a shrine near Kitano Tenmangu Shrine. I...,yes,Japanese,view review,"tensor([[ 2.0541e-01, 6.3483e-03, 6.2157e-01...",32,99,"['2.0541e-01', ' 6.3483e-03', ' 6.2157e-01',..."
8402,美藤研一,2023-06-10 22:05:13,5,0,I have been to the Hydrangea garden every yea...,yes,Japanese,view review,"tensor([[ 1.8021e-01, 5.9837e-02, 6.9239e-01...",85,99,"['1.8021e-01', ' 5.9837e-02', ' 6.9239e-01',..."
6602,Jack L,2023-06-13 11:34:47,5,0,Another must visit for any visit to Kyoto. The...,yes,NaN,view review,"tensor([[ 2.3856e-01, 5.6699e-02, 6.5816e-01...",69,99,"['2.3856e-01', ' 5.6699e-02', ' 6.5816e-01',..."

In [13]:
# T = np.zeros((91,91))

# aoi_list = trj['aid'].values.tolist()
# # aoi_list
# for trj in aoi_list:
#     trj_list = trj.split(',')
#     for i in range(0,len(trj_list)):
#         j = i + 1
#         if (j >= len(trj_list)):
#             break
#         if (trj_list[i] != trj_list[j]):
#             T[int(trj_list[i])][int(trj_list[j])] += 1
#             # if(T[aoi_list[i]][aoi_list[j]]>1):
#             #     print(T[aoi_list[i]][aoi_list[j]])

# T
T = np.zeros((91,91))

aoi_list = trj['aid'].values.tolist()
trj_list = trj['clustr_id'].values.tolist()

for i in range(len(aoi_list)):
    j = i + 1
    if (j >= len(aoi_list)):
        break
    if (trj_list[i] == trj_list[j] and aoi_list[i] != aoi_list[j]):
        T[aoi_list[i]][aoi_list[j]] += 1
        # if(T[aoi_list[i]][aoi_list[j]]>1):
        #     print(T[aoi_list[i]][aoi_list[j]])

T

array([[0., 0., 3., ..., 0., 1., 0.],
       [1., 0., 4., ..., 0., 1., 2.],
       [1., 3., 0., ..., 2., 2., 2.],
       ...,
       [4., 1., 1., ..., 0., 1., 0.],
       [2., 3., 1., ..., 0., 0., 3.],
       [0., 3., 2., ..., 2., 0., 0.]])

In [14]:
with open('T_Gmap.plk', '+bw') as f:
    pickle.dump(T, f)