In [8]:
import numpy as np
import pickle
import pandas as pd

In [9]:
trj = pd.read_csv("classify_latest.csv")
trj

,Author,Date,Rating,Helpful count,Review,Picture included,Language,(view source),tensor,aid,clustr_id,vec_2d
0,Vas,2015-11-17 01:09:04,4,2,If you're a tourist looking to explore a relig...,no,NaN,view review,"tensor([[ 1.7520e-01, 1.1550e-02, 5.9349e-01...",0,14,"['1.7520e-01', ' 1.1550e-02', ' 5.9349e-01',..."
1,Martin Reindl,2015-12-10 07:24:44,5,2,The Enryakuji temple complex on Mount Hiei is ...,no,NaN,view review,"tensor([[ 1.6719e-01, -8.4652e-02, 5.2984e-01...",0,54,"['1.6719e-01', ' -8.4652e-02', ' 5.2984e-01',..."
2,Erik Visser,2016-06-15 03:01:48,4,2,Hiking up to and down from the the monastery c...,no,NaN,view review,"tensor([[ 3.1461e-01, 2.0650e-01, 6.4538e-01...",0,35,"['3.1461e-01', ' 2.0650e-01', ' 6.4538e-01',..."
3,Paradise Walker,2017-02-13 21:22:42,5,2,Amazing temple which has been designated as a ...,yes,NaN,view review,"tensor([[ 1.3496e-01, -1.1500e-01, 6.0431e-01...",0,78,"['1.3496e-01', ' -1.1500e-01', ' 6.0431e-01',..."
4,Steven Lee,2017-03-16 07:33:08,5,2,I can say that this building is the biggest bu...,no,NaN,view review,"tensor([[ 1.9209e-01, 1.0050e-01, 6.2991e-01...",0,22,"['1.9209e-01', ' 1.0050e-01', ' 6.2991e-01',..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8999,高田久司,2023-04-01 23:48:27,5,0,"On Sunday, March 26, 2023, I visited the stat...",no,Japanese,view review,"tensor([[-4.1604e-01, -1.9089e-01, 1.1752e-01...",90,5,"['-4.1604e-01', ' -1.9089e-01', ' 1.1752e-01'..."
9000,_ Penman,2023-04-18 20:26:56,3,0,"From April to August, places where you can vi...",no,Japanese,view review,"tensor([[ 3.5845e-01, 7.5652e-02, 6.8562e-01...",90,17,"['3.5845e-01', ' 7.5652e-02', ' 6.8562e-01',..."
9001,マコラ天使,2023-04-20 07:32:35,5,0,I went to the autumn special exhibition. The ...,no,Japanese,view review,"tensor([[ 2.4746e-01, 2.1381e-01, 6.7655e-01...",90,80,"['2.4746e-01', ' 2.1381e-01', ' 6.7655e-01',..."
9002,居場嘉津治,2023-04-22 04:33:58,4,1,"It is the head temple of Shugendo, located at...",yes,Japanese,view review,"tensor([[-3.4147e-01, -2.4622e-01, -4.4683e-03...",90,5,"['-3.4147e-01', ' -2.4622e-01', ' -4.4683e-03'..."
9003,michy,2023-06-08 14:26:44,5,0,I learned a little more about Yamabushi.,yes,Japanese,view review,"tensor([[ 3.1449e-01, 2.5263e-01, 7.4339e-01...",90,38,"['3.1449e-01', ' 2.5263e-01', ' 7.4339e-01',..."

In [10]:
trj = trj.sort_values(['clustr_id', 'Date'])
trj

,Author,Date,Rating,Helpful count,Review,Picture included,Language,(view source),tensor,aid,clustr_id,vec_2d
3204,ann tsai,2013-06-17 15:09:49,5,0,Good,no,NaN,view review,"tensor([[ 2.0482e-01, 3.3107e-01, 1.0315e+00...",39,0,"['2.0482e-01', ' 3.3107e-01', ' 1.0315e+00',..."
2104,Satoru Sato,2013-09-02 14:11:36,3,0,NaN,no,NaN,view review,"tensor([[ 2.0871e-01, 3.2975e-01, 1.0317e+00...",29,0,"['2.0871e-01', ' 3.2975e-01', ' 1.0317e+00',..."
4809,Patrick KalonjiTV,2014-08-09 03:54:44,5,0,Wow,no,NaN,view review,"tensor([[ 2.1687e-01, 3.2893e-01, 1.0362e+00...",53,0,"['2.1687e-01', ' 3.2893e-01', ' 1.0362e+00',..."
4810,Tú NguyễnNgoc,2015-02-26 11:18:57,5,0,My Dream,no,NaN,view review,"tensor([[ 2.0344e-01, 3.3022e-01, 1.0196e+00...",53,0,"['2.0344e-01', ' 3.3022e-01', ' 1.0196e+00',..."
1103,Chan mun kay,2015-04-16 06:58:29,4,0,Thanks,no,NaN,view review,"tensor([[ 2.1265e-01, 3.2680e-01, 1.0406e+00...",19,0,"['2.1265e-01', ' 3.2680e-01', ' 1.0406e+00',..."
...,...,...,...,...,...,...,...,...,...,...,...,...
4902,N,2023-05-30 15:24:51,5,0,"If you walk east from Demachiyanagi, you will...",yes,Japanese,view review,"tensor([[ 2.0703e-01, -4.1640e-02, 6.2501e-01...",53,99,"['2.0703e-01', ' -4.1640e-02', ' 6.2501e-01',..."
6702,えーちゃん2,2023-06-01 08:26:36,4,0,I visited Honen Shonin's 25 sacred grounds. I...,yes,Japanese,view review,"tensor([[ 2.0904e-01, 3.8601e-02, 5.7566e-01...",7,99,"['2.0904e-01', ' 3.8601e-02', ' 5.7566e-01',..."
2603,時々旅人,2023-06-04 08:17:14,5,1,It is a shrine near Kitano Tenmangu Shrine. I...,yes,Japanese,view review,"tensor([[ 2.0541e-01, 6.3483e-03, 6.2157e-01...",32,99,"['2.0541e-01', ' 6.3483e-03', ' 6.2157e-01',..."
8402,美藤研一,2023-06-10 22:05:13,5,0,I have been to the Hydrangea garden every yea...,yes,Japanese,view review,"tensor([[ 1.8021e-01, 5.9837e-02, 6.9239e-01...",85,99,"['1.8021e-01', ' 5.9837e-02', ' 6.9239e-01',..."
6602,Jack L,2023-06-13 11:34:47,5,0,Another must visit for any visit to Kyoto. The...,yes,NaN,view review,"tensor([[ 2.3856e-01, 5.6699e-02, 6.5816e-01...",69,99,"['2.3856e-01', ' 5.6699e-02', ' 6.5816e-01',..."

In [11]:
S = np.zeros((91,24))

aoi_list = trj['aid'].values.tolist()
checkin = trj['Date'].values.tolist()

checkin_hour = []
for daytime in checkin:
    checkin_hour.append(int(daytime.split(' ')[1].split(':')[0]))

for i in range(len(aoi_list)):
    S[aoi_list[i]][checkin_hour[i]] += 1

S

array([[3., 3., 5., ..., 2., 1., 5.],
       [6., 4., 5., ..., 2., 2., 1.],
       [4., 2., 4., ..., 1., 1., 6.],
       ...,
       [3., 4., 3., ..., 1., 3., 1.],
       [5., 4., 6., ..., 4., 4., 3.],
       [1., 3., 6., ..., 3., 2., 5.]])

In [12]:
with open('S_Gmap.plk', '+bw') as f:
    pickle.dump(S, f)

In [16]:
with open('S2.plk','rb') as f:
    S2 = pickle.load(f)
S2

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 4.,  0.,  0., ..., 47., 16., 14.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])